apiVersion: v1
name: victoria-metrics-agent
description: Victoria Metrics Agent - collects metrics from various sources and stores them to VictoriaMetrics
version: 0.8.41
appVersion: v1.91.3
sources:
- https://github.com/VictoriaMetrics/helm-charts
